insert into public.profile_questions (
  group_key, group_label, group_description,
  key, label, question_type, required,
  min_value, max_value, default_numeric, default_text, badge_min, badge_max,
  select_options
)
values
  ('basics', 'Basics', 'A few details so your partner knows who you are.',
   'display-name', 'What should we call you?', 'text', true,
   2, 32, null, '', null, null, null),
  ('basics', 'Basics', 'A few details so your partner knows who you are.',
   'age', 'How old are you?', 'numeric', true,
   18, 120, 18, null, null, null, null),

  ('communication', 'Communication', 'How you talk about problems and preferences.',
   'bring-up-directly', 'When something bothers you, how likely are you to bring it up directly?', 'slide', true,
   1, 5, 3, null, 'I almost never bring it up', 'I say it pretty directly', null),
  ('communication', 'Communication', 'How you talk about problems and preferences.',
   'hints-over-talks', 'I prefer hints and vibes over direct talks about problems.', 'slide', true,
   1, 5, 3, null, 'Strongly disagree', 'Strongly agree', null),

  ('emotional-openness', 'Emotional openness', 'How you share feelings and vulnerabilities.',
   'share-fears', 'How comfortable are you sharing your fears and insecurities with a partner?', 'slide', true,
   1, 5, 3, null, 'Not comfortable', 'Very comfortable', null),
  ('emotional-openness', 'Emotional openness', 'How you share feelings and vulnerabilities.',
   'keep-feelings-private', 'I like to keep my deeper feelings to myself.', 'slide', true,
   1, 5, 3, null, 'Strongly disagree', 'Strongly agree', null),

  ('initiative', 'Initiative', 'Who plans and starts romantic moments.',
   'plans-romantic-activities', 'How often do you like to be the one who plans romantic activities?', 'select', true,
   null, null, null, 'sometimes', null, null,
   '[{"value":"never","label":"Never"},{"value":"sometimes","label":"Sometimes"},{"value":"often","label":"Often"},{"value":"very-often","label":"Very often"}]'::jsonb),
  ('initiative', 'Initiative', 'Who plans and starts romantic moments.',
   'starts-gestures', 'In an ideal relationship, who usually starts romantic gestures?', 'select', true,
   null, null, null, 'take-turns', null, null,
   '[{"value":"mostly-partner","label":"Mostly my partner"},{"value":"take-turns","label":"We take turns"},{"value":"mostly-me","label":"Mostly me"}]'::jsonb),

  ('playfulness', 'Playfulness', 'Teasing, humor, and keeping things light.',
   'teasing-importance', 'How important is playful teasing and jokes in your relationship?', 'slide', true,
   1, 5, 3, null, 'Not important', 'Very important', null),
  ('playfulness', 'Playfulness', 'Teasing, humor, and keeping things light.',
   'conflict-humor', 'In conflicts, I prefer to keep things light and defuse with humor.', 'slide', true,
   1, 5, 3, null, 'Strongly disagree', 'Strongly agree', null),

  ('planning', 'Planning', 'Weekends, spontaneity, and surprises.',
   'weekend-preference', 'On a free weekend, I prefer...', 'select', true,
   null, null, null, 'mix', null, null,
   '[{"value":"planned","label":"Planned dates and activities"},{"value":"mix","label":"A mix of planned and spontaneous"},{"value":"spontaneous","label":"Mostly spontaneous decisions"}]'::jsonb),
  ('planning', 'Planning', 'Weekends, spontaneity, and surprises.',
   'last-minute-surprises', 'Last-minute surprises make me feel...', 'select', true,
   null, null, null, 'neutral', null, null,
   '[{"value":"stressed","label":"Stressed"},{"value":"neutral","label":"Neutral"},{"value":"excited","label":"Excited"}]'::jsonb),

  ('affection', 'Affection', 'Physical touch and PDA.',
   'physical-private', 'How comfortable are you with physical affection (hugs, cuddles, kisses) in private?', 'slide', true,
   1, 5, 3, null, 'Not comfortable', 'Very comfortable', null),
  ('affection', 'Affection', 'Physical touch and PDA.',
   'pda', 'Public displays of affection (PDA) are...', 'select', true,
   null, null, null, 'okay-small', null, null,
   '[{"value":"uncomfortable","label":"Uncomfortable"},{"value":"okay-small","label":"Okay in small doses"},{"value":"totally-fine","label":"Totally fine"},{"value":"enjoy","label":"I enjoy them a lot"}]'::jsonb),

  ('togetherness', 'Togetherness', 'Time together and alone time.',
   'evenings-per-week', 'How many evenings per week do you ideally like to spend together?', 'numeric', true,
   0, 7, 3, null, null, null, null),
  ('togetherness', 'Togetherness', 'Time together and alone time.',
   'alone-time', 'In a relationship, personal alone time is...', 'select', true,
   null, null, null, 'somewhat', null, null,
   '[{"value":"not-important","label":"Not important"},{"value":"somewhat","label":"Somewhat important"},{"value":"very","label":"Very important"}]'::jsonb),

  ('conflict', 'Conflict', 'How you handle disagreements.',
   'approach', 'When conflict appears, I tend to...', 'select', true,
   null, null, null, 'wait-then-talk', null, null,
   '[{"value":"avoid","label":"Avoid and hope it passes"},{"value":"wait-then-talk","label":"Wait a bit, then talk"},{"value":"talk-directly","label":"Talk about it quickly and directly"}]'::jsonb),
  ('conflict', 'Conflict', 'How you handle disagreements.',
   'raised-voices', 'Raised voices in arguments make me want to...', 'select', true,
   null, null, null, 'stay-tense', null, null,
   '[{"value":"shut-down","label":"Shut down"},{"value":"stay-tense","label":"Stay but feel tense"},{"value":"keep-talking","label":"Keep talking to resolve it"}]'::jsonb)
on conflict (key) do update set
  group_key           = excluded.group_key,
  group_label         = excluded.group_label,
  group_description   = excluded.group_description,
  label               = excluded.label,
  question_type       = excluded.question_type,
  required            = excluded.required,
  min_value           = excluded.min_value,
  max_value           = excluded.max_value,
  default_numeric     = excluded.default_numeric,
  default_text        = excluded.default_text,
  badge_min           = excluded.badge_min,
  badge_max           = excluded.badge_max,
  select_options      = excluded.select_options;
